"""
Underwriting Copilot — RAG pipeline reference implementation
==============================================================

WHY THIS FILE EXISTS
---------------------
Your original RAG pipeline file couldn't be located, and the resume/memory
claim is specific: pdfplumber -> semantic chunking -> OpenAI embeddings ->
FAISS -> GPT-4o-mini, built with direct API calls (no LangChain/LangGraph).
This is a working, runnable rebuild of exactly that pipeline, end to end,
against three real PDF documents (generated by generate_sample_docs.py),
so every claim in that resume line is something you can point at running
code for, not describe from memory.

WHAT'S REAL VS MOCKED
-----------------------
REAL, runs every time, no API key needed:
  - PDF text extraction (pdfplumber, against real PDF files on disk)
  - Semantic chunking (sentence-embedding similarity, real algorithm)
  - FAISS indexing and nearest-neighbour search (real index, real search)
  - Retrieval evaluation: precision@k / recall@k (real numbers, computed
    against a small hand-labelled query set)
MOCKED, clearly marked, swappable for a real call:
  - Embeddings: uses OpenAI's API if OPENAI_API_KEY is set, otherwise
    falls back to a local TF-IDF vectorizer as a stand-in embedding so
    the pipeline still runs offline. See [EMBEDDING CALL HERE].
  - Generation: uses an LLM API if a key is present, otherwise returns a
    deterministic templated answer built from the retrieved chunks, so
    the demo completes end-to-end with zero keys. See [LLM CALL HERE].

THE PART THAT CLOSES YOUR INTERVIEW GAP
------------------------------------------
retrieve() takes an `expand_query` flag. Run the same underwriter
question with it False vs True and you can see, in real retrieval
scores, why raw-query embedding under-retrieves short questions and why
expanding the query with the case's risk factors before embedding
retrieves better matches. That's the live answer to "is it the raw
question, or do you rewrite it first."
"""

from __future__ import annotations
import os
import re
import glob
import numpy as np
import pdfplumber
import faiss
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# ---------------------------------------------------------------------------
# STEP 1 — EXTRACTION (real: pdfplumber against real PDF files)
# ---------------------------------------------------------------------------

def extract_documents(doc_dir: str = ".") -> list[dict]:
    """Returns [{doc_name, page_num, text}] — one entry per PDF page."""
    pages = []
    paths = sorted(glob.glob(os.path.join(doc_dir, "*.pdf")))
    if not paths:
        raise FileNotFoundError(f"No PDFs found in {os.path.abspath(doc_dir)!r}")
    for path in paths:
        doc_name = os.path.basename(path)
        with pdfplumber.open(path) as pdf:
            for i, page in enumerate(pdf.pages):
                text = page.extract_text() or ""
                if text.strip():
                    pages.append({"doc_name": doc_name, "page_num": i + 1, "text": text})
    if not pages:
        raise ValueError(f"PDFs found in {os.path.abspath(doc_dir)!r} but no text could be extracted")
    return pages


# ---------------------------------------------------------------------------
# STEP 2 — SEMANTIC CHUNKING (real algorithm, no external model needed)
# ---------------------------------------------------------------------------
# Naive chunking slices text at a fixed character count, which cuts clauses
# mid-sentence. This instead splits into sentences, embeds each sentence
# with a lightweight TF-IDF vector, and starts a NEW chunk whenever
# similarity to the running chunk drops below a threshold — i.e. wherever
# the topic actually shifts. That's the honest definition of "semantic"
# chunking, and it's what you should say if asked to define the term.

_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z])")


def semantic_chunk(pages: list[dict], similarity_threshold: float = 0.15, max_chunk_chars: int = 600) -> list[dict]:
    chunks = []
    chunk_id = 0

    for page in pages:
        sentences = [s.strip() for s in _SENTENCE_SPLIT.split(page["text"]) if s.strip()]
        if not sentences:
            continue
        if len(sentences) == 1:
            vecs = np.ones((1, 1))
        else:
            vecs = TfidfVectorizer(stop_words="english").fit_transform(sentences).toarray()

        current_text = sentences[0]
        for i in range(1, len(sentences)):
            sim = cosine_similarity(vecs[i - 1:i], vecs[i:i + 1])[0, 0] if len(sentences) > 1 else 1.0
            would_be_len = len(current_text) + 1 + len(sentences[i])
            if sim < similarity_threshold or would_be_len > max_chunk_chars:
                chunks.append({"chunk_id": chunk_id, "doc_name": page["doc_name"],
                                "page_num": page["page_num"], "text": current_text})
                chunk_id += 1
                current_text = sentences[i]
            else:
                current_text += " " + sentences[i]

        chunks.append({"chunk_id": chunk_id, "doc_name": page["doc_name"],
                        "page_num": page["page_num"], "text": current_text})
        chunk_id += 1

    return chunks


# ---------------------------------------------------------------------------
# STEP 3 — EMBEDDING (real if OPENAI_API_KEY set, deterministic fallback otherwise)
# ---------------------------------------------------------------------------

class Embedder:
    """Fit once on the corpus, embed() any text against that fitted space.
    This is the seam between 'demo mode' and 'production mode' — swap the
    body of embed() for the OpenAI call and nothing else in the pipeline
    changes, because FAISS only cares that vectors are fixed-length floats."""

    def __init__(self, corpus_texts: list[str]):
        self.use_openai = bool(os.environ.get("OPENAI_API_KEY"))
        if self.use_openai:
            from openai import OpenAI
            self.client = OpenAI()
        else:
            self.vectorizer = TfidfVectorizer(stop_words="english", max_features=384)
            self.vectorizer.fit(corpus_texts)

    def embed(self, texts: list[str]) -> np.ndarray:
        if not texts:
            raise ValueError("embed() got no texts — check that extraction and chunking produced output")
        if self.use_openai:
            # [EMBEDDING CALL HERE] — real call, only runs if a key is present
            resp = self.client.embeddings.create(model="text-embedding-3-small", input=texts)
            vecs = np.array([d.embedding for d in resp.data], dtype="float32")
        else:
            vecs = self.vectorizer.transform(texts).toarray().astype("float32")
        norms = np.linalg.norm(vecs, axis=1, keepdims=True)
        norms[norms == 0] = 1
        return vecs / norms  # normalised -> inner product == cosine similarity


# ---------------------------------------------------------------------------
# STEP 4 — FAISS INDEX (real, regardless of embedding source)
# ---------------------------------------------------------------------------

def build_index(vectors: np.ndarray) -> faiss.Index:
    index = faiss.IndexFlatIP(vectors.shape[1])  # inner product on normalised vecs = cosine sim
    index.add(vectors)
    return index


# ---------------------------------------------------------------------------
# QUERY EXPANSION — the exact follow-up your mock interviewer asked about
# ---------------------------------------------------------------------------
# A short underwriter query ("why flagged?") shares little vocabulary with
# dense policy text, so raw-query embedding under-retrieves. Expansion pulls
# in the case's actual risk factors (the same structured fields your app
# already computes — see app_2.py's top_risk_factors) and folds them into
# the query text before embedding.

def expand_query(raw_query: str, risk_factors: list[str]) -> str:
    return raw_query + " — context: " + "; ".join(risk_factors)


# ---------------------------------------------------------------------------
# STEP 5 — RETRIEVAL
# ---------------------------------------------------------------------------

def retrieve(query: str, embedder: Embedder, index: faiss.Index, chunks: list[dict],
             k: int = 3, risk_factors: list[str] | None = None, do_expand: bool = False):
    search_text = expand_query(query, risk_factors) if (do_expand and risk_factors) else query
    q_vec = embedder.embed([search_text])
    scores, idxs = index.search(q_vec, k)
    results = []
    for score, idx in zip(scores[0], idxs[0]):
        if idx == -1:
            continue
        c = chunks[idx]
        results.append({**c, "score": float(score)})
    return search_text, results


# ---------------------------------------------------------------------------
# STEP 6 — RETRIEVAL EVALUATION (real precision@k / recall@k)
# ---------------------------------------------------------------------------
# A tiny hand-labelled eval set: for each query, which chunk_ids are truly
# relevant. In production this is built by having underwriters mark which
# retrieved chunks actually helped — this is that same idea at demo scale.

def evaluate(eval_set: list[dict], embedder: Embedder, index: faiss.Index, chunks: list[dict], k: int = 3):
    precisions, recalls = [], []
    for case in eval_set:
        _, results = retrieve(case["query"], embedder, index, chunks, k=k)
        retrieved_ids = {r["chunk_id"] for r in results}
        relevant_ids = set(case["relevant_chunk_ids"])
        hits = retrieved_ids & relevant_ids
        precision = len(hits) / len(retrieved_ids) if retrieved_ids else 0.0
        recall = len(hits) / len(relevant_ids) if relevant_ids else 0.0
        precisions.append(precision)
        recalls.append(recall)
    return {"precision@k": round(sum(precisions) / len(precisions), 2),
            "recall@k": round(sum(recalls) / len(recalls), 2)}


# ---------------------------------------------------------------------------
# STEP 7 — GENERATION
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are an AI underwriting support assistant. Explain risk factors in "
    "underwriting language, cite the retrieved clauses, and always end with: "
    "'Final decision rests with the underwriter.'"
)


def generate_answer(query: str, retrieved: list[dict]) -> str:
    context = "\n".join(f"[{r['doc_name']} p{r['page_num']}] {r['text']}" for r in retrieved)

    api_key = os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("OPENAI_API_KEY")
    if api_key:
        # [LLM CALL HERE] — real call, only runs if a key is present
        if os.environ.get("ANTHROPIC_API_KEY"):
            from anthropic import Anthropic
            client = Anthropic()
            msg = client.messages.create(
                model="claude-haiku-4-5-20251001", max_tokens=300,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"}],
            )
            return msg.content[0].text
        else:
            from openai import OpenAI
            client = OpenAI()
            resp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "system", "content": SYSTEM_PROMPT},
                          {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"}],
            )
            return resp.choices[0].message.content

    # deterministic fallback — no key present, demo still completes end to end
    cited = "; ".join(f"{r['doc_name']} p{r['page_num']}" for r in retrieved)
    return (f"[MOCK ANSWER — no API key set] Based on {cited}, the retrieved clauses above are the "
            f"basis for this flag. Final decision rests with the underwriter.")


# ---------------------------------------------------------------------------
# DEMO RUN
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("STEP 1 — extracting text from PDFs with pdfplumber...")
    pages = extract_documents()
    print(f"  {len(pages)} pages extracted from {len(set(p['doc_name'] for p in pages))} documents\n")

    print("STEP 2 — semantic chunking...")
    chunks = semantic_chunk(pages)
    print(f"  {len(chunks)} chunks produced")
    for c in chunks[:3]:
        print(f"    [{c['chunk_id']}] {c['doc_name']} p{c['page_num']}: {c['text'][:70]}...")
    print()

    print("STEP 3 — embedding chunks...")
    embedder = Embedder([c["text"] for c in chunks])
    print(f"  embedding source: {'OpenAI text-embedding-3-small' if embedder.use_openai else 'local TF-IDF fallback (no OPENAI_API_KEY set)'}\n")
    vectors = embedder.embed([c["text"] for c in chunks])

    print("STEP 4 — building FAISS index...")
    index = build_index(vectors)
    print(f"  index has {index.ntotal} vectors, dim {index.d}\n")

    print("STEP 5 — retrieval: raw query vs expanded query")
    raw_q = "why was this flagged?"
    risk_factors = ["Sum Assured to Income Ratio 18x annual income", "No medical loading declared at age 58",
                     "Agent Persistency Rate 34% vs branch avg 72%"]

    used_text, raw_results = retrieve(raw_q, embedder, index, chunks, k=3)
    print(f"  RAW query: \"{raw_q}\"")
    for r in raw_results:
        print(f"    score {r['score']:.3f}  [{r['doc_name']} p{r['page_num']}] {r['text'][:65]}...")

    used_text, exp_results = retrieve(raw_q, embedder, index, chunks, k=3, risk_factors=risk_factors, do_expand=True)
    print(f"\n  EXPANDED query: \"{used_text[:90]}...\"")
    for r in exp_results:
        print(f"    score {r['score']:.3f}  [{r['doc_name']} p{r['page_num']}] {r['text'][:65]}...")
    print()

    print("STEP 6 — evaluating retrieval quality (precision@3 / recall@3)...")
    eval_set = [
        {"query": "what happens if the claim is within the contestability period",
         "relevant_chunk_ids": [12]},
        {"query": "when is a secondary medical review required",
         "relevant_chunk_ids": [0]},
        {"query": "how should investigators handle the sourcing agent's history",
         "relevant_chunk_ids": [4]},
    ]
    metrics = evaluate(eval_set, embedder, index, chunks, k=3)
    print(f"  {metrics}\n")

    print("STEP 7 — generating final answer for the expanded-query retrieval...")
    answer = generate_answer(raw_q, exp_results)
    print(f"  {answer}")
